/* CLEAR CACHE */
alter system flush shared_pool;

/* VIEW SERVER HOST NAME */
select host_name from v$instance;

/* CHECK CURREN SID (session ID) */
select sys_context('userenv','sessionid') Session_ID from dual;

/* VENDORS TABLE CREATION */ ------------------------------------------------------------------------------
DROP TABLE VENDORS;
CREATE TABLE VENDORS 
(
  ID NUMBER(10,0) NOT NULL 
, VENDORNAME NCHAR(200) NOT NULL 
, CONSTRAINT VENDORS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

DROP SEQUENCE VENDORS_SEQ;
CREATE SEQUENCE VENDORS_SEQ;

DROP TRIGGER VENORS_TRG;
CREATE TRIGGER VENDORS_TRG 
BEFORE INSERT ON VENDORS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT VENDORS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

-----------------------------------------------------------------------------------------------
 
/* VENDORS TABLE INSERT */---------------------------------------------------------------------
INSERT INTO VENDORS (VENDORNAME) 
VALUES('Iablanska Halva corp.');
INSERT INTO VENDORS (VENDORNAME) 
VALUES('Kamenitza corp.');
INSERT INTO VENDORS (VENDORNAME) 
VALUES('Zagorka corp.');
INSERT INTO VENDORS (VENDORNAME) 
VALUES('Carlsberg Bulgaria corp.');
INSERT INTO VENDORS (VENDORNAME) 
VALUES('Boliarka BT corp.');
INSERT INTO VENDORS (VENDORNAME) 
VALUES('Burgaska Konserva corp.');
INSERT INTO VENDORS (VENDORNAME) 
VALUES('Dedo Stafid ET.');

/* MEASURES TABLE CREATION */-----------------------------------------------------------
DROP TABLE MEASURES;
CREATE TABLE MEASURES 
(
  ID NUMBER(10,0) NOT NULL 
, MEASURENAME NCHAR(200) NOT NULL 
, CONSTRAINT MEASURES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

DROP SEQUENCE MEASURES_SEQ;
CREATE SEQUENCE MEASURES_SEQ;

DROP TRIGGER MEASURES_TRG;
CREATE TRIGGER MEASURES_TRG 
BEFORE INSERT ON MEASURES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MEASURES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

/* MEASURES TABLE INSERT */------------------------------------------------------------------
INSERT INTO MEASURES (MEASURENAME)
VALUES ('liters');
INSERT INTO MEASURES (MEASURENAME)
VALUES ('pieces');
INSERT INTO MEASURES (MEASURENAME)
VALUES ('grams');
INSERT INTO MEASURES (MEASURENAME)
VALUES ('kilograms');
INSERT INTO MEASURES (MEASURENAME)
VALUES ('meters');
INSERT INTO MEASURES (MEASURENAME)
VALUES ('centimeters');
INSERT INTO MEASURES (MEASURENAME)
VALUES ('milimeters');
INSERT INTO MEASURES (MEASURENAME)
VALUES ('packages');
INSERT INTO MEASURES (MEASURENAME)
VALUES ('boxes');
INSERT INTO MEASURES (MEASURENAME)
VALUES ('trucks');
--------------------------------------------------------------------------------------

/* PRODUCTS TABLE CREATION */ -------------------------------------------------------------------
DROP TABLE PRODUCTS;
CREATE TABLE PRODUCTS 
(
  ID NUMBER(10, 0) NOT NULL 
, VENDORID NUMBER(10, 0) NOT NULL 
, PRODUCTNAME NCHAR(200) NOT NULL 
, MEASUREID NUMBER(10, 0) NOT NULL 
, PRICE NUMBER(19, 4) NOT NULL
, CONSTRAINT PRODUCTS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE
, CONSTRAINT PRODUCTS_MEASURES_FK 
  FOREIGN KEY (MEASUREID) REFERENCES MEASURES (ID)
  ENABLE
, CONSTRAINT PRODUCTS_VENDORS_FK 
  FOREIGN KEY (VENDORID) REFERENCES VENDORS (ID)
  ENABLE
);

DROP SEQUENCE PRODUCTS_SEQ;
CREATE SEQUENCE PRODUCTS_SEQ;

DROP TRIGGER PRODUCTS_TRG;
CREATE TRIGGER PRODUCTS_TRG 
BEFORE INSERT ON PRODUCTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PRODUCTS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

/* PRODUCTS INSERTS */----------------------------------------------------------------------

INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE)
VALUES(1,'Halva',3,2.55);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE)
VALUES(6,'Konserva "Skumria v Sobstven Sos"',3,1.80);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE)
VALUES(6,'Konserva "Giuvech"',3,3.33);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE)
VALUES(7,'Fastuci "Pechena Semka"',3,1.70);

INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(2,'Beer "Astika"',1,1.80);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(2,'Beer "Becks"',1,1.55);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(2,'Beer "Staropramen"',1,1.66);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(2,'Beer "Slavena"',1,1.10);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(2,'Beer "Burgasko"',1,1.20);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(2,'Beer "Stella Artois"',1,1.70);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(2,'Beer "Kamenitza"',1,1.40);

INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(3,'Beer "Ariana"',1,1.20);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(3,'Beer "Zagorka"',1,1.50);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(3,'Beer "Stolichno"',1,2.00);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(3,'Beer "Amstel"',1,2.20);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(3,'Beer "Heineken"',1,2.50);

INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(4,'Beer "Shumensko"',1,1.20);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(4,'Beer "Pirinsko"',1,1.20);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(4,'Beer "Carlsberg"',1,1.80);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(4,'Beer "Tuborg"',1,1.70);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(4,'Beer "Budvaiser"',1,2.10);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(4,'Beer "Holsten"',1,1.50);

INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(5,'Beer "Boliarka"',1,1.30);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(5,'Beer "Balkansko"',1,1.20);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(5,'Beer "Diana"',1,1.40);
INSERT INTO PRODUCTS (VENDORID,PRODUCTNAME,MEASUREID,PRICE) 
VALUES(5,'Beer "Caltenberg"',1,1.80);

COMMIT;
