//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MEASURE> MEASURES { get; set; }
        public virtual DbSet<ORA_ASPNET_APPLICATIONS> ORA_ASPNET_APPLICATIONS { get; set; }
        public virtual DbSet<ORA_ASPNET_MEMBERSHIP> ORA_ASPNET_MEMBERSHIP { get; set; }
        public virtual DbSet<ORA_ASPNET_PATHS> ORA_ASPNET_PATHS { get; set; }
        public virtual DbSet<ORA_ASPNET_PERSONALIZNPERUSER> ORA_ASPNET_PERSONALIZNPERUSER { get; set; }
        public virtual DbSet<ORA_ASPNET_PROFILE> ORA_ASPNET_PROFILE { get; set; }
        public virtual DbSet<ORA_ASPNET_ROLES> ORA_ASPNET_ROLES { get; set; }
        public virtual DbSet<ORA_ASPNET_SESSIONAPPLICATIONS> ORA_ASPNET_SESSIONAPPLICATIONS { get; set; }
        public virtual DbSet<ORA_ASPNET_SESSIONS> ORA_ASPNET_SESSIONS { get; set; }
        public virtual DbSet<ORA_ASPNET_SITEMAP> ORA_ASPNET_SITEMAP { get; set; }
        public virtual DbSet<ORA_ASPNET_USERS> ORA_ASPNET_USERS { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
        public virtual DbSet<VENDOR> VENDORS { get; set; }
        public virtual DbSet<ORA_ASPNET_PERSONALIZNALLUSERS> ORA_ASPNET_PERSONALIZNALLUSERS { get; set; }
    
        public virtual int ORA_ASPNET_CREATEPAGE(byte[] aPPID, string pAGE, ObjectParameter pAGEID)
        {
            var aPPIDParameter = aPPID != null ?
                new ObjectParameter("APPID", aPPID) :
                new ObjectParameter("APPID", typeof(byte[]));
    
            var pAGEParameter = pAGE != null ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORA_ASPNET_CREATEPAGE", aPPIDParameter, pAGEParameter, pAGEID);
        }
    
        public virtual int ORA_ASPNET_CREATEUSER(byte[] aPPLICATIONID_, string uSERNAME_, Nullable<decimal> iSUSERANONYMOUS, Nullable<System.DateTime> lASTACTIVITYDATE_, ObjectParameter uSERID_)
        {
            var aPPLICATIONID_Parameter = aPPLICATIONID_ != null ?
                new ObjectParameter("APPLICATIONID_", aPPLICATIONID_) :
                new ObjectParameter("APPLICATIONID_", typeof(byte[]));
    
            var uSERNAME_Parameter = uSERNAME_ != null ?
                new ObjectParameter("USERNAME_", uSERNAME_) :
                new ObjectParameter("USERNAME_", typeof(string));
    
            var iSUSERANONYMOUSParameter = iSUSERANONYMOUS.HasValue ?
                new ObjectParameter("ISUSERANONYMOUS", iSUSERANONYMOUS) :
                new ObjectParameter("ISUSERANONYMOUS", typeof(decimal));
    
            var lASTACTIVITYDATE_Parameter = lASTACTIVITYDATE_.HasValue ?
                new ObjectParameter("LASTACTIVITYDATE_", lASTACTIVITYDATE_) :
                new ObjectParameter("LASTACTIVITYDATE_", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORA_ASPNET_CREATEUSER", aPPLICATIONID_Parameter, uSERNAME_Parameter, iSUSERANONYMOUSParameter, lASTACTIVITYDATE_Parameter, uSERID_);
        }
    
        public virtual int ORA_ASPNET_GETSITEMAPDATA(string aPPLICATIONNAME_)
        {
            var aPPLICATIONNAME_Parameter = aPPLICATIONNAME_ != null ?
                new ObjectParameter("APPLICATIONNAME_", aPPLICATIONNAME_) :
                new ObjectParameter("APPLICATIONNAME_", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORA_ASPNET_GETSITEMAPDATA", aPPLICATIONNAME_Parameter);
        }
    
        public virtual int ORA_ASPNET_LOGWEBEVENTS(string eVENTID, Nullable<System.DateTime> eVENTTIMEUTC, Nullable<System.DateTime> eVENTTIME, string eVENTTYPE, Nullable<decimal> eVENTSEQUENCE, Nullable<decimal> eVENTOCCURENCE, Nullable<decimal> eVENTCODE, Nullable<decimal> eVENTDETAILCODE, string mESSAGE, string aPPLICATIONPATH, string aPPLICATIONVIRTUALPATH, string mACHINENAME, string rEQUESTURL, string eXCEPTIONTYPE, string dETAILS)
        {
            var eVENTIDParameter = eVENTID != null ?
                new ObjectParameter("EVENTID", eVENTID) :
                new ObjectParameter("EVENTID", typeof(string));
    
            var eVENTTIMEUTCParameter = eVENTTIMEUTC.HasValue ?
                new ObjectParameter("EVENTTIMEUTC", eVENTTIMEUTC) :
                new ObjectParameter("EVENTTIMEUTC", typeof(System.DateTime));
    
            var eVENTTIMEParameter = eVENTTIME.HasValue ?
                new ObjectParameter("EVENTTIME", eVENTTIME) :
                new ObjectParameter("EVENTTIME", typeof(System.DateTime));
    
            var eVENTTYPEParameter = eVENTTYPE != null ?
                new ObjectParameter("EVENTTYPE", eVENTTYPE) :
                new ObjectParameter("EVENTTYPE", typeof(string));
    
            var eVENTSEQUENCEParameter = eVENTSEQUENCE.HasValue ?
                new ObjectParameter("EVENTSEQUENCE", eVENTSEQUENCE) :
                new ObjectParameter("EVENTSEQUENCE", typeof(decimal));
    
            var eVENTOCCURENCEParameter = eVENTOCCURENCE.HasValue ?
                new ObjectParameter("EVENTOCCURENCE", eVENTOCCURENCE) :
                new ObjectParameter("EVENTOCCURENCE", typeof(decimal));
    
            var eVENTCODEParameter = eVENTCODE.HasValue ?
                new ObjectParameter("EVENTCODE", eVENTCODE) :
                new ObjectParameter("EVENTCODE", typeof(decimal));
    
            var eVENTDETAILCODEParameter = eVENTDETAILCODE.HasValue ?
                new ObjectParameter("EVENTDETAILCODE", eVENTDETAILCODE) :
                new ObjectParameter("EVENTDETAILCODE", typeof(decimal));
    
            var mESSAGEParameter = mESSAGE != null ?
                new ObjectParameter("MESSAGE", mESSAGE) :
                new ObjectParameter("MESSAGE", typeof(string));
    
            var aPPLICATIONPATHParameter = aPPLICATIONPATH != null ?
                new ObjectParameter("APPLICATIONPATH", aPPLICATIONPATH) :
                new ObjectParameter("APPLICATIONPATH", typeof(string));
    
            var aPPLICATIONVIRTUALPATHParameter = aPPLICATIONVIRTUALPATH != null ?
                new ObjectParameter("APPLICATIONVIRTUALPATH", aPPLICATIONVIRTUALPATH) :
                new ObjectParameter("APPLICATIONVIRTUALPATH", typeof(string));
    
            var mACHINENAMEParameter = mACHINENAME != null ?
                new ObjectParameter("MACHINENAME", mACHINENAME) :
                new ObjectParameter("MACHINENAME", typeof(string));
    
            var rEQUESTURLParameter = rEQUESTURL != null ?
                new ObjectParameter("REQUESTURL", rEQUESTURL) :
                new ObjectParameter("REQUESTURL", typeof(string));
    
            var eXCEPTIONTYPEParameter = eXCEPTIONTYPE != null ?
                new ObjectParameter("EXCEPTIONTYPE", eXCEPTIONTYPE) :
                new ObjectParameter("EXCEPTIONTYPE", typeof(string));
    
            var dETAILSParameter = dETAILS != null ?
                new ObjectParameter("DETAILS", dETAILS) :
                new ObjectParameter("DETAILS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORA_ASPNET_LOGWEBEVENTS", eVENTIDParameter, eVENTTIMEUTCParameter, eVENTTIMEParameter, eVENTTYPEParameter, eVENTSEQUENCEParameter, eVENTOCCURENCEParameter, eVENTCODEParameter, eVENTDETAILCODEParameter, mESSAGEParameter, aPPLICATIONPATHParameter, aPPLICATIONVIRTUALPATHParameter, mACHINENAMEParameter, rEQUESTURLParameter, eXCEPTIONTYPEParameter, dETAILSParameter);
        }
    
        public virtual int ORA_ASPNET_PAU_GETPGSETTINGS(string aPPNAME, string pAGE, ObjectParameter pAGESETTINGS)
        {
            var aPPNAMEParameter = aPPNAME != null ?
                new ObjectParameter("APPNAME", aPPNAME) :
                new ObjectParameter("APPNAME", typeof(string));
    
            var pAGEParameter = pAGE != null ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORA_ASPNET_PAU_GETPGSETTINGS", aPPNAMEParameter, pAGEParameter, pAGESETTINGS);
        }
    
        public virtual int ORA_ASPNET_PAU_RESETPGSETTINGS(string aPPNAME, string pAGE)
        {
            var aPPNAMEParameter = aPPNAME != null ?
                new ObjectParameter("APPNAME", aPPNAME) :
                new ObjectParameter("APPNAME", typeof(string));
    
            var pAGEParameter = pAGE != null ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORA_ASPNET_PAU_RESETPGSETTINGS", aPPNAMEParameter, pAGEParameter);
        }
    
        public virtual int ORA_ASPNET_PAU_SETPGSETTINGS(string aPPNAME, string pAGE, ObjectParameter pAGESETTINGS_, Nullable<System.DateTime> cURRENTTIME)
        {
            var aPPNAMEParameter = aPPNAME != null ?
                new ObjectParameter("APPNAME", aPPNAME) :
                new ObjectParameter("APPNAME", typeof(string));
    
            var pAGEParameter = pAGE != null ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(string));
    
            var cURRENTTIMEParameter = cURRENTTIME.HasValue ?
                new ObjectParameter("CURRENTTIME", cURRENTTIME) :
                new ObjectParameter("CURRENTTIME", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORA_ASPNET_PAU_SETPGSETTINGS", aPPNAMEParameter, pAGEParameter, pAGESETTINGS_, cURRENTTIMEParameter);
        }
    
        public virtual int ORA_ASPNET_PA_FINDSTATE(string sCOPE, string aPPNAME, string pAGE, Nullable<decimal> pAGEINDEX, Nullable<decimal> pAGESIZE, ObjectParameter tOTALRECORDS, string uSRNAME, Nullable<System.DateTime> iNACTIVESINCEDATE)
        {
            var sCOPEParameter = sCOPE != null ?
                new ObjectParameter("SCOPE", sCOPE) :
                new ObjectParameter("SCOPE", typeof(string));
    
            var aPPNAMEParameter = aPPNAME != null ?
                new ObjectParameter("APPNAME", aPPNAME) :
                new ObjectParameter("APPNAME", typeof(string));
    
            var pAGEParameter = pAGE != null ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(string));
    
            var pAGEINDEXParameter = pAGEINDEX.HasValue ?
                new ObjectParameter("PAGEINDEX", pAGEINDEX) :
                new ObjectParameter("PAGEINDEX", typeof(decimal));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(decimal));
    
            var uSRNAMEParameter = uSRNAME != null ?
                new ObjectParameter("USRNAME", uSRNAME) :
                new ObjectParameter("USRNAME", typeof(string));
    
            var iNACTIVESINCEDATEParameter = iNACTIVESINCEDATE.HasValue ?
                new ObjectParameter("INACTIVESINCEDATE", iNACTIVESINCEDATE) :
                new ObjectParameter("INACTIVESINCEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORA_ASPNET_PA_FINDSTATE", sCOPEParameter, aPPNAMEParameter, pAGEParameter, pAGEINDEXParameter, pAGESIZEParameter, tOTALRECORDS, uSRNAMEParameter, iNACTIVESINCEDATEParameter);
        }
    
        public virtual int ORA_ASPNET_PA_GETCOUNTOFSTATE(string sCOPE, string aPPNAME, string pAGE, ObjectParameter cOUNT, string uSRNAME, Nullable<System.DateTime> iNACTIVESINCEDATE)
        {
            var sCOPEParameter = sCOPE != null ?
                new ObjectParameter("SCOPE", sCOPE) :
                new ObjectParameter("SCOPE", typeof(string));
    
            var aPPNAMEParameter = aPPNAME != null ?
                new ObjectParameter("APPNAME", aPPNAME) :
                new ObjectParameter("APPNAME", typeof(string));
    
            var pAGEParameter = pAGE != null ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(string));
    
            var uSRNAMEParameter = uSRNAME != null ?
                new ObjectParameter("USRNAME", uSRNAME) :
                new ObjectParameter("USRNAME", typeof(string));
    
            var iNACTIVESINCEDATEParameter = iNACTIVESINCEDATE.HasValue ?
                new ObjectParameter("INACTIVESINCEDATE", iNACTIVESINCEDATE) :
                new ObjectParameter("INACTIVESINCEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORA_ASPNET_PA_GETCOUNTOFSTATE", sCOPEParameter, aPPNAMEParameter, pAGEParameter, cOUNT, uSRNAMEParameter, iNACTIVESINCEDATEParameter);
        }
    
        public virtual int ORA_ASPNET_PA_RESETSHAREDSTATE(ObjectParameter rESETCOUNT, string aPPNAME, string pAGE)
        {
            var aPPNAMEParameter = aPPNAME != null ?
                new ObjectParameter("APPNAME", aPPNAME) :
                new ObjectParameter("APPNAME", typeof(string));
    
            var pAGEParameter = pAGE != null ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORA_ASPNET_PA_RESETSHAREDSTATE", rESETCOUNT, aPPNAMEParameter, pAGEParameter);
        }
    
        public virtual int ORA_ASPNET_PA_RESETUSERSTATE(ObjectParameter rESETCOUNT, string aPPNAME, string pAGE, Nullable<System.DateTime> iNACTIVESINCEDATE, string uSRNAME)
        {
            var aPPNAMEParameter = aPPNAME != null ?
                new ObjectParameter("APPNAME", aPPNAME) :
                new ObjectParameter("APPNAME", typeof(string));
    
            var pAGEParameter = pAGE != null ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(string));
    
            var iNACTIVESINCEDATEParameter = iNACTIVESINCEDATE.HasValue ?
                new ObjectParameter("INACTIVESINCEDATE", iNACTIVESINCEDATE) :
                new ObjectParameter("INACTIVESINCEDATE", typeof(System.DateTime));
    
            var uSRNAMEParameter = uSRNAME != null ?
                new ObjectParameter("USRNAME", uSRNAME) :
                new ObjectParameter("USRNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORA_ASPNET_PA_RESETUSERSTATE", rESETCOUNT, aPPNAMEParameter, pAGEParameter, iNACTIVESINCEDATEParameter, uSRNAMEParameter);
        }
    
        public virtual int ORA_ASPNET_PPU_GETPGSETTINGS(string aPPNAME, string pAGE, ObjectParameter pAGESETTINGS, string uSRNAME, Nullable<System.DateTime> cURRENTTIME)
        {
            var aPPNAMEParameter = aPPNAME != null ?
                new ObjectParameter("APPNAME", aPPNAME) :
                new ObjectParameter("APPNAME", typeof(string));
    
            var pAGEParameter = pAGE != null ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(string));
    
            var uSRNAMEParameter = uSRNAME != null ?
                new ObjectParameter("USRNAME", uSRNAME) :
                new ObjectParameter("USRNAME", typeof(string));
    
            var cURRENTTIMEParameter = cURRENTTIME.HasValue ?
                new ObjectParameter("CURRENTTIME", cURRENTTIME) :
                new ObjectParameter("CURRENTTIME", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORA_ASPNET_PPU_GETPGSETTINGS", aPPNAMEParameter, pAGEParameter, pAGESETTINGS, uSRNAMEParameter, cURRENTTIMEParameter);
        }
    
        public virtual int ORA_ASPNET_PPU_RESETPGSETTINGS(string aPPNAME, string pAGE, string uSRNAME, Nullable<System.DateTime> cURRENTTIME)
        {
            var aPPNAMEParameter = aPPNAME != null ?
                new ObjectParameter("APPNAME", aPPNAME) :
                new ObjectParameter("APPNAME", typeof(string));
    
            var pAGEParameter = pAGE != null ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(string));
    
            var uSRNAMEParameter = uSRNAME != null ?
                new ObjectParameter("USRNAME", uSRNAME) :
                new ObjectParameter("USRNAME", typeof(string));
    
            var cURRENTTIMEParameter = cURRENTTIME.HasValue ?
                new ObjectParameter("CURRENTTIME", cURRENTTIME) :
                new ObjectParameter("CURRENTTIME", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORA_ASPNET_PPU_RESETPGSETTINGS", aPPNAMEParameter, pAGEParameter, uSRNAMEParameter, cURRENTTIMEParameter);
        }
    
        public virtual int ORA_ASPNET_PPU_SETPGSETTINGS(string aPPNAME, string pAGE, ObjectParameter pAGESETTINGS_, Nullable<System.DateTime> cURRENTTIME, string uSRNAME)
        {
            var aPPNAMEParameter = aPPNAME != null ?
                new ObjectParameter("APPNAME", aPPNAME) :
                new ObjectParameter("APPNAME", typeof(string));
    
            var pAGEParameter = pAGE != null ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(string));
    
            var cURRENTTIMEParameter = cURRENTTIME.HasValue ?
                new ObjectParameter("CURRENTTIME", cURRENTTIME) :
                new ObjectParameter("CURRENTTIME", typeof(System.DateTime));
    
            var uSRNAMEParameter = uSRNAME != null ?
                new ObjectParameter("USRNAME", uSRNAME) :
                new ObjectParameter("USRNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ORA_ASPNET_PPU_SETPGSETTINGS", aPPNAMEParameter, pAGEParameter, pAGESETTINGS_, cURRENTTIMEParameter, uSRNAMEParameter);
        }
    }
}
