//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JasenOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.SALES = new HashSet<SALE>();
        }
    
        public int ID { get; set; }
        public int VENDORID { get; set; }
        public string PRODUCTNAME { get; set; }
        public int MEASUREID { get; set; }
        public decimal PRICE { get; set; }
    
        public virtual MEASURE MEASURE { get; set; }
        public virtual ICollection<SALE> SALES { get; set; }
        public virtual VENDOR VENDOR { get; set; }
    }
}
