//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JasenOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE
    {
        public int ID { get; set; }
        public System.DateTime SALE_DATE { get; set; }
        public int PRODUCT_ID { get; set; }
        public int SUPERMARKET_ID { get; set; }
        public decimal QUANTITY { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SUPERMARKET SUPERMARKET { get; set; }
    }
}
