//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JasenOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPERMARKET
    {
        public SUPERMARKET()
        {
            this.SALES = new HashSet<SALE>();
        }
    
        public int ID { get; set; }
        public string SUPERMARKET_NAME { get; set; }
    
        public virtual ICollection<SALE> SALES { get; set; }
    }
}
